CRITICAL - 2023-11-29 02:52:26 --> Encrypter needs a starter key.
in SYSTEMPATH\Encryption\Encryption.php on line 126.
 1 SYSTEMPATH\Encryption\Encryption.php(126): CodeIgniter\Encryption\Exceptions\EncryptionException::forNeedsStarterKey()
 2 SYSTEMPATH\Config\Services.php(252): CodeIgniter\Encryption\Encryption->initialize(Object(Config\Encryption))
 3 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::encrypter()
 4 APPPATH\Controllers\BaseController.php(78): CodeIgniter\Config\BaseService::__callStatic('encrypter', [])
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
 6 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-29 02:54:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\PropertyPrime\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\PropertyPrime\app\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
#7 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\PropertyPrime\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\PropertyPrime\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\PropertyPrime\app\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
#6 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\PropertyPrime\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-11-29 02:54:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `event_category`
ORDER BY `ecategory_name` ASC', [], false)
 3 APPPATH\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
 5 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-11-29 02:54:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-11-29 02:54:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\PropertyPrime\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\PropertyPrime\app\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
#7 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\PropertyPrime\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\PropertyPrime\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\PropertyPrime\app\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
#6 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\PropertyPrime\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-11-29 02:54:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `event_category`
ORDER BY `ecategory_name` ASC', [], false)
 3 APPPATH\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
 5 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-11-29 02:56:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-11-29 02:56:12 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'property_prime' in C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'zaq12wsx', 'property_prime', 3306, '', 0)
#1 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\PropertyPrime\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\PropertyPrime\app\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
#7 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\PropertyPrime\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'property_prime' in C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\PropertyPrime\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\PropertyPrime\app\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
#6 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\PropertyPrime\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-11-29 02:56:12 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'property_prime'
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `event_category`
ORDER BY `ecategory_name` ASC', [], false)
 3 APPPATH\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
 5 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-11-29 02:57:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-11-29 02:57:23 --> mysqli_sql_exception: Table 'eptm.properties' doesn't exist in C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\PropertyPrime\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\PropertyPrime\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\PropertyPrime\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\PropertyPrime\app\Controllers\Property.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(942): App\Controllers\Property->index()
#8 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Property))
#9 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\PropertyPrime\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-11-29 02:57:23 --> Table 'eptm.properties' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `properties`
WHERE `properties`.`deleted_at` IS NULL', [], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Property.php(12): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Property->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Property))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-11-29 03:09:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-11-29 03:09:47 --> mysqli_sql_exception: Table 'property_prime.event_category' doesn't exist in C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PropertyPrime\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\PropertyPrime\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\PropertyPrime\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\PropertyPrime\app\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
#7 C:\xampp\htdocs\PropertyPrime\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\PropertyPrime\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-11-29 03:09:47 --> Table 'property_prime.event_category' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `event_category`
ORDER BY `ecategory_name` ASC', [], false)
 2 APPPATH\Controllers\BaseController.php(86): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
 4 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
